### ISSUE TITLE
Notification of new applications

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#21]
There should ideally be an email sent to certain people when a new application is posted.
This list could be defined in the back end somewhere.
This would really improve our speed of processing.

**Comment by tyler274** [comment]
This could be done via a check of users with the recruiter role with an email put into the task queue for all of them on creation of an application

**Comment by erinlessard** [comment]
could there be a task queue for this only that executes every 15-30m or so?

**Comment by tyler274** [comment]
Yes, there actually already is a task queue running in the background to keep the corporation and alliance data updated and to check api validity.
