### ISSUE TITLE
Pager on "history" page doesn't work

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#24]
https://recruit.karmafleet.org/recruits/application_queue/history/

can't page to page 2

**Comment by erinlessard** [comment]
seems to be back

**Comment by tyler274** [comment]
working as intended. 

history needs to be paginated or it will not work with enough apps :(

**Comment by erinlessard** [comment]
https://recruit.karmafleet.org/recruits/application_queue/all/

You may as well remove this part then. It functions the same as the regular queue expect the pagination doesn't work. What was the point of it again? I think it was something I requested but I've forgotten why,

**Comment by tyler274** [comment]
it does not, the /all/ route gives all apps that have not been processed (i.e. accept or reject). history is a record of ALL apps
