### ISSUE TITLE
Application questions

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#3]
How long have you been playing EVE?
Any notable accomplishments in that time?
Walk us through your Corporation history:
Why are you leaving your current Corporation?
What do you know about KarmaFleet / How do you expect daily life in KarmaFleet to be?
Are any of your characters bought, and if so, which ones? (Include links to EVE-O forum sales threads)
Why are you interested in joining KarmaFleet?
On a scale from 1 to 10, where 1 is pure PvE and 10 is pure PvP, where do you see yourself?
Select options:
1 (Pure PVE)
2
3
4
5 (Equal PVE and PVP)
6
7
8
9
10 (Pure PVP)
What PVP fleet role do you enjoy the most?
How did you find out about KarmaFleet?

**Comment by tyler274** [comment]
done
