### ISSUE TITLE
New fields on application page

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#30]
ADD
"Have you ever interacted with another member of Goonswarm Federation?"
"Do you have any friends in KarmaFleet? If so, who?"

REMOVE
"How did you find out about KarmaFleet?"

CHANGE
"What do you know about KarmaFleet?" -> "What do you know about KarmaFleet and how did you find out about KarmaFleet?"

**Comment by tyler274** [comment]
I broke the later 2 questions in two as porkbutte mentioned earlier that bundling questions doesn't always go well

**Comment by tyler274** [comment]
done and implemented
