### ISSUE TITLE
Front page of recruitment app content

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#4]
(This would go on the front page, probably as the only content. It should be a easy to read and will be updated at a later point in time)

How to (successfully) join KarmaFleet using this website(aka a test in instruction following):

1) Create an account 
2) Add FULL account API keys for ALL of your characters
3) Submit a new application HERE(link: https://recruit.karmafleet.org/recruits/applications/create/), or through the application page in the navigation menu.
4) Answer all the questions with as much detail as possible and submit the application.
5) After submitting your application, find it in your list of submitted applications and click on the blue eye icon under "actions".
6) Copy the address/URL of your application. Apply in game on your main character, pasting the application address/URL into the in game application.
7) Wait for a recruiter to review your application and accept you.

**Comment by tyler274** [comment]
implemented
