### ISSUE TITLE
Additional application statuses

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#42]
Please add additional application statues for our workflow:
"Role Stasis"
"Awaiting Response"

Also change "pending" (a brand new app) to "New"

**Comment by erinlessard** [comment]
Also "Needs Director Review"

**Comment by tyler274** [comment]
Need button colors

**Comment by erinlessard** [comment]
selecting "awaiting response" or "needs director review" closes the application, the same as rejecting. "role stasis" works as expected, though.

**Comment by erinlessard** [comment]
selecting any of the 3 new options does not show the application in the application queue. Only rejected/accepted application statuses should NOT show up in the application queue, everything else should.

**Comment by erinlessard** [comment]
The new statuses also do show up on any application listings, they just have a blank empty status.

**Comment by tyler274** [comment]
NEVER NOT COMMIT CODE WHEN EXTREMELY TIRED

**Comment by erinlessard** [comment]
"Closed", "Needs Processing"
