### ISSUE TITLE
Change status panels on application list page to be alerts so we have colored backgrounds

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#43]
alert-success for accepted
alert-danger for declined
alert-warning for pending/new(rename as per other ticket)
alert-info for in progress/role stasis/awaiting response

**Comment by tyler274** [comment]
did you mean change the table row background as well?

**Comment by erinlessard** [comment]
no, it's working as intended now.

Can you change the director review's alert class to danger, ex:

<td data-title="Status" class="text-center">

```
                                        <div class="alert-danger" role="alert">Needs Director Review</div>


                                </td>
```
