### ISSUE TITLE
Error 404/500 when adding API?

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#45]
Apparently some people started having issues when adding APIs. They get 404 errors and/or 500's. Here's all I know:

"I have been having issues signing up on the website. When I try to add my API key it will 404. However, it takes my API key down but will not show any charcters. When I go to the API management page and click the refresh API button it gives me error 500. I have tried on chrome, Internet explorer and the in-game browser."

"I am trying to add characters to the website so I can fill out an application. However, when I try to click the blue button on the API I get sent to https://recruit.karmafleet.org/users/api_update/4250346 and it returns as a 404 Not Found. As such I can't add any characters in order to proceed with the application process.

Thanks in advance for any help you might provide."

As well as this post:
http://www.reddit.com/r/Karmafleet/comments/32bbtw/api_update/

**Comment by erinlessard** [comment]
Getting more and more people reporting about this issue.

**Comment by erinlessard** [comment]
Maybe related to being blacklisted by API servers for breaking the rate limit.
https://forums.eveonline.com/default.aspx?g=posts&t=366921

**Comment by ggrog** [comment]
Are people still complaining about this?
