### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#52]
Every character should be checked against the blacklist, including after they add a new API and alts. 

Blacklist status should be shown somewhere easy to see on the application page. Blacklist information such as reason should be shown on the application page as well.

Blacklist should be accessible by any recruiter role and only editable by admin role. Blacklist information should include who added it, a reason, any characters, and an optional IP. All blacklist entries should work based on characters and IPs.

Adding a new entry to the blacklist should be able to be done manually by entering the required information, OR by a button on the application page, which automatically adds all characters on the application to the blacklist, and the IP.

**Comment by tyler274** [comment]
first version is done and up. 

adding a button soonish

**Comment by tyler274** [comment]
still gotta add that button
