### ISSUE TITLE
New API Masks + Show new API data

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#63]
Can you add the API mask from https://developers.eveonline.com/blog/article/chat-channel-info-available-in-xml-api  into our required API 

as well as add the information from that new API mask somewhere on an application?

**Comment by tyler274** [comment]
ATM I rely on API jacknife to display that information, which has yet to add it. 

So as to the later: Maybe.

**Comment by erinlessard** [comment]
ok well the "full api" masks comparison needs to be updated to include the new mask as well as people are idiots and don't click the "make full api" link. they then make a full API with chat info and put it in and whine when it doesn't work so update asap tia

**Comment by erinlessard** [comment]
the new API mask part needs to be done sooner then later

**Comment by tyler274** [comment]
api mask added, will switch to new jacknife at some point
