### ISSUE TITLE
Blacklist checking characters on an application needs to be more accurate

### ISSUE THREAD

**Issue by erinlessard** [tyler274/Recruitment-App#69]
It is still matching partials of name such as any generic last name. Extremely annoying and generates tons of false positives. Easy fix is doing a select against blacklist table.

SELECT \* FROM blacklisttable WHERE name = 'name';

Shouldn't be any joins or magic required.

**Comment by tyler274** [comment]
switched to a query, hopefully i did it right :P

**Comment by ggrog** [comment]
Looks like this is fixed.
